sparkpost_requeue.settings:
  type: config_object
  label: 'Sparkpost requeue config.'
  mapping:
    enable:
      type: boolean
      label: 'Enable sparkpost requeue'
    max_retries:
      type: integer
      label: 'Max retries'
    minimum_time:
      type: integer
      label: 'Minimum time'
