sparkpost.settings:
  type: config_object
  label: 'Sparkpost config.'
  mapping:
    api_key:
      type: text
      label: 'Api key'
    debug:
      type: boolean
      label: 'Debug mode'
    sender:
      type: email
      label: 'Sender email'
    sender_name:
      type: text
      label: 'Sender name'
    format:
      label: 'Format to format message'
      type: text
    async:
      type: boolean
      label: 'Send async'
    skip_cron:
      type: boolean
      label: 'Skip queue on cron'
