# @file
# .travis.yml - Configurable pager styles.

language: php

sudo: required

php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    # Drupal paths.
    - DRUPAL_STAGING_DIR="$HOME/drupal_staging"
    - DRUPAL_PATH="$HOME/drupal8"
    - PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"

    # Testing environment variables.
    - SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal_travis_db
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8080

    # Suppress deprecation handling.
    #- SYMFONY_DEPRECATIONS_HELPER=disabled

cache:
  directories:
    - $DRUPAL_STAGING_DIR
    - $HOME/.composer/cache

services:
  - mysql

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:

  # Remove  XDebug.
  - phpenv config-rm xdebug.ini || true

  # Create the test db.
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal_travis_db;'

  # Stage Drupal codebase.
  - |
      if [[ ! -f $DRUPAL_STAGING_DIR/index.php ]]; then
        git clone --depth=5 --branch=8.8.x http://git.drupal.org/project/drupal.git $DRUPAL_STAGING_DIR
        # composer config minimum-stability dev
        cd $DRUPAL_STAGING_DIR
        composer install --no-progress --no-suggest
        composer require drupal/console symfony/var-dumper --no-progress --no-suggest
        composer update phpunit/phpunit phpspec/prophecy --with-dependencies --no-progress
      fi

  # Copy staged codebase to live.
  - cp -r $DRUPAL_STAGING_DIR/. $DRUPAL_PATH

  # Require drupal/pagerer from the source just cloned from GitHub.
  - cd $TRAVIS_BUILD_DIR
  - git checkout -b travisci-run-branch
  - cd $DRUPAL_PATH
  - |
      composer config repositories.travisci-run '{"type": "path", "url": "$TRAVIS_BUILD_DIR", "options": {"symlink": false}}'
  - composer require "drupal/pagerer:dev-travisci-run-branch" --no-progress --no-suggest

install:
  - cd $DRUPAL_PATH/core
  - drupal server 127.0.0.1:8080 &
  - sleep 4s

before_script:
  - cd $DRUPAL_PATH/core

script:
  #- ../vendor/bin/phpunit --group Pagerer
  - ../vendor/bin/phpunit ../modules/contrib/pagerer/tests/src/Functional/PagererTest.php

notifications:
  email: false
